Repository homebaseio/homebase-react, pull requests merged in 2020-12, with the labels that each got.

#39 fix(errors): humanize missing context error
  src/homebase/react.cljs
Labels: documentation

#40 feat(entity): humanize entity for console logs
  js/tests/benchmarks.test.js
  src/homebase/js.cljs
  src/homebase/js_test.cljs
  src/homebase/react.cljs
Labels: enhancement, needs QA

#43 fix(query): bools and combined queries
  src/homebase/js.cljs
  src/homebase/js_test.cljs
Labels: bug

#41 docs(prs): add pull request template
  .github/pull_request_template.md
Labels: documentation
