Repository homebaseio/homebase-react, pull requests merged in 2020-11, with the labels that each got.

#6 Add clarity to readme
  README.md
Labels: documentation

#7 Setup CLJS tests via node and CI
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .github/workflows/publish-examples.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  shadow-cljs.edn
  src/homebase/js_test.cljs
  src/test/core.cljs
  yarn.lock
Labels: enhancement

#3 Benchmarks
  .github/workflows/ci.yml
  .gitignore
  README.md
  js/.babelrc
  js/README.md
  js/counter-example.jsx
  js/tests/benchmarks.test.js
  package.json
  src/js_gen/counter-example.js
  src/js_gen/todo-example.js
  yarn.lock
Labels: enhancement

#8 Add badges to readme
  README.md
Labels: documentation

#5 Make errors more informative and friendly
  package.json
  src/homebase/js.cljs
  src/homebase/js_test.cljs
  src/homebase/react.cljs
Labels: documentation, enhancement

#10 chore(cd): release to npm with cd
  .github/workflows/cd.yml
  .releaserc.json
  CHANGELOG.md
  README.md
  package.json
  yarn.lock
Labels: enhancement

#12 docs(todo-example): clarify schema comments
  js/todo-example.jsx
  src/js_gen/todo-example.js
Labels: documentation

#13 ci: document and enforce our contribution protocols
  .husky/.gitignore
  .husky/commit-msg
  .husky/prepare-commit-msg
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  commitlint.config.js
  package.json
  yarn.lock
Labels: documentation

#14 build(npm): remove ci and cd code from releases
  .npmignore
Labels: enhancement

#15 perf(entity.get): add attribute change tracking
  .github/workflows/publish-examples.yml
  README.md
  js/todo-example.jsx
  package.json
  shadow-cljs.edn
  src/homebase/js.cljs
  src/homebase/js_test.cljs
  src/homebase/react.cljs
  src/js_gen/todo-example.js
Labels: enhancement

#16 Typescript definitions
  .github/workflows/ci.yml
  bundle-ts.sh
  jest.config.js
  package.json
  types/index.d.ts
  types/tests/index.test-d.ts
  yarn.lock
Labels: enhancement

#17 fix(index.d.ts): add string to useQuery query types
  types/index.d.ts
  types/tests/index.test-d.ts
Labels: bug

#19 feat(homebase.react): add useClient hook
  README.md
  js/todo-firebase-example.jsx
  package.json
  public/css/firebaseui.css
  public/index.html
  src/example/core.cljs
  src/example/todo_firebase.cljs
  src/homebase/js.cljs
  src/homebase/react.cljs
  src/js_gen/todo-firebase-example.js
  yarn.lock
Labels: enhancement, needs QA

#20 fix(client): help goog closure compiler
  src/homebase/js.cljs
  src/homebase/react.cljs
Labels: bug

#21 fix(config): gracefully handle empty schema object
  src/homebase/js.cljs
Labels: bug

#26 fix(get): humanize missing ref error
  src/homebase/js.cljs
  src/homebase/js_test.cljs
  src/homebase/react.cljs
Labels: documentation

#27 docs(readme.md): correct spelling of removeTransactListener
  README.md
Labels: documentation

#25 docs(readme.md): refactor readme to be more focused, added logo
  README.md
  public/images/logo-blk.png
Labels: documentation

#28 fix(entity): attr access with advanved compilation
  src/homebase/js.cljs
  src/homebase/react.cljs
Labels: bug

#29 fix(datom): attr access
  src/homebase/react.cljs
Labels: bug

#23 fix(index.d.ts): add typescript type declaration for useClient react hook
  types/index.d.ts
Labels: enhancement

#30 fix(ts): simplify ts script
  bundle-ts.sh
  package.json
Labels: bug

#24 fix(index.d.ts): add jsdoc strings
  types/index.d.ts
Labels: documentation

#31 fix(types): useClient returns Array
  types/index.d.ts
Labels: bug
