Repository homebaseio/homebase-react, pull requests merged in 2021-03, with the labels that each got.

#70 docs(README): write-heavy readme
  README.md
Labels: documentation

#71 docs(roam): add plausible
  examples/roam/public/index.html
Labels: documentation

#72 fix(dx): alias schema to lookup helpers
  README.md
  docs/0300|Tutorial.md
  docs/0400|API.md
  examples/counter/package.json
  examples/counter/yarn.lock
  examples/roam/package.json
  examples/roam/src/App.js
  examples/roam/yarn.lock
  examples/todo/package.json
  examples/todo/src/App.js
  examples/todo/yarn.lock
  examples/typescript-firebase-todo/package.json
  examples/typescript-firebase-todo/src/App.tsx
  examples/typescript-firebase-todo/yarn.lock
  src/dev/example/js/array.jsx
  src/dev/example/js/todo-firebase.jsx
  src/dev/example/js/todo.jsx
  src/dev/example/js_compiled/array.js
  src/dev/example/js_compiled/todo-firebase.js
  src/dev/example/js_compiled/todo.js
  src/homebase/js.cljs
  src/homebase/js_test.cljs
  src/homebase/react.cljs
  src/homebase/react.test.js
  types/index.d.ts
Labels: enhancement

#73 build(examples): upgrade homebase-react
  examples/counter/package.json
  examples/counter/yarn.lock
  examples/roam/package.json
  examples/roam/yarn.lock
  examples/todo/package.json
  examples/todo/yarn.lock
  examples/typescript-firebase-todo/package.json
  examples/typescript-firebase-todo/yarn.lock
Labels: dependencies
